export default [
  "get-all-meals",
  "get-all-categories",
  "get-all-ingredients",
  "get-template-meals",
  "apply-templates",
  "delete-own-templates",
  "update-own-templates",
  "get-all-templates",
  "create-templates",
  "create-meals",
  "create-categories",
  "create-ingredients",
  "update-meals",
  "update-categories",
  "update-ingredients",
  "delete-meals",
  "delete-categories",
  "delete-ingredients",
] as const;
